server:
  port: 8080

spring:
  profiles:
    active: qa # default profile

---

spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: shadow
    url: jdbc:mysql://localhost:3306/shadowapp-qa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to Shadow!

management:
  endpoints:
    web:
      exposure:
        include: "*" # include everything
        exclude: "env, beans" # excluding two endpoints

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: shadow
    url: jdbc:mysql://localhost:3306/shadowapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to Shadow!

---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: shadow
    url: jdbc:mysql://localhost:3306/shadowapp-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to Shadow!